### ISSUE TITLE
Option to change data folder

### ISSUE THREAD

**Issue by brunocarlin** [wlandau/targets-stan#6]
## Prework

* [ x] I understand and agree to this repository's [code of conduct](https://github.com/wlandau/targets-manual/blob/master/CODE_OF_CONDUCT.md).
* [ x] I understand and agree to this repository's [contributing guidelines](https://github.com/wlandau/targets-manual/blob/master/CONTRIBUTING.md).
* [ x] New features take time and effort to create, and they take even more effort to maintain. So if the purpose of the feature is to resolve a struggle you are encountering personally, please consider first posting a "trouble" or "other" issue so we can discuss your use case and search for existing solutions first.

## Proposal

It would be helpfull to change the data folder to the same folder that my package is using, that way the data files would get exported and I could document them on roxygen

**Comment by brunocarlin** [comment]
ops sorry wrong package I meant to request this feature in targets but still this would be useful in targets-stan as well

**Comment by wlandau** [comment]
In that case, I will close this issue here.

> It would be helpfull to change the data folder to the same folder that my package is using, that way the data files would get exported and I could document them on roxygen

You are talking about the `_targets/` data store folder, right? `targets` deliberately enforces strict guardrails: the folder is always called `_targets/`, and it is always at the project root (where you call `tar_make()`). This will never change in `targets`, and for good reasons: consistency, dependability, and safety in order to keep users from getting themselves into trouble ([background here](https://wlandau.github.io/targets/articles/need.html#better-guardrails-by-design)).

To work around this, you can export the data you need as a [dynamic file target](https://wlandau.github.io/targets-manual/files.html#external-output-files).

There is already a thread at https://github.com/wlandau/targets/issues/129, and we can continue there if you want.
